### ISSUE TITLE
Should we replace the links of techministry.gr with lambdaspace.gr ?

### ISSUE THREAD

**Issue by sortingbubbles** [SheSharpGr/shesharpgr.github.io#20]
Our web page has many links to [techministry.gr](https://techministry.gr/) in the events section. 
Now that the brand has changed, should we change them to [lambdaspace.gr](https://lambdaspace.gr/)?

**Comment by AndyFou** [comment]
Mmm good question, I guess yes! 
But perhaps the names should remain Tech Ministry, for consistency with the Posters?

**Comment by katerinakat** [comment]
Καλύτερα ναι, μπορούμε να βάλουμε lambdaspace.gr και σε παρένθεση (ex
Tech-Ministry.gr).

On Wed, Oct 5, 2016 at 4:04 PM, Antigoni M. Founta <notifications@github.com
